### PR TITLE
Aboveground data update with a few other fixes

### PR DESCRIPTION
**Pull request by mgrigri1**
I've added all the aboveground data. It's all tidy and ready to go, and I made functions that pull each data set. They look good, but don't work yet. Error occurs when trying to find the data file with read_csv_file(). Note sure what's going on there. I've added all the data (from google drive) into the inst/extdata/ folder, but the function can't find them...In other news, this is my first pull request so apologies if I'm doing something wrong here!

### CODE REVIEW

**Comment by bpbond** [comment]
👏  @mgrigri1 !

If it's OK I'm going to push some fixes here.

**Comment by bpbond** [comment]
I have cleaned up the documentation a bit, renamed a `subplot` column to `subplot_id` for consistency, and added some basic tests.

Two large problems remain:

1. @mgrigri1 Can you open up `inst/extdata/forte_table_metadata.csv` and add field descriptions, including units, for your new tables? If you have questions about how to do this lmk.
2. @atkinsjeff The package tests are generating huge numbers of warnings, it looks like on some file read. Do you know about this? It needs to be fixed; lmk if you have time, otherwise I will.

**Comment by mgrigri1** [comment]
Alright @bpbond, I edited the 'inst/extdata/forte_table_metadata.csv' , lmk what else I can/should do

**Comment by bpbond** [comment]
@mgrigri1 The `fd_seedling_sapling_xxxx.csv` files have the word "new" in some entries of the `height_total_cm` field. Why?  Does it need to be there? It's causing what should be a numeric column to become character, which isn't great.

**Comment by mgrigri1** [comment]
@bpbond Alrighty, I made the fix to the data files and uploaded the new files. Should be good on that issue.

**Comment by bpbond** [comment]
Thanks Max. I'm going to tackle the crazy number of warnings in the test suite; makes it impossible to see real problems.

**Comment by bpbond** [comment]
@atkinsjeff @mgrigri1  `fortedata` now passes all tests, as well as R CMD CHECK, cleanly on my machine.

**Comment by atkinsjeff** [comment]
merging in Max's changes

**Pull request merged**
