### PR TITLE
Rs figure

### PR DESCRIPTION
**Pull request by stephpenn1**

### CODE REVIEW

**Review by atkinsjeff — COMMENTED** [review]
edited to:   

````{r table_soil_respiration}
make_table(md, "fd_soil_respiration")
pal <- viridis(4, begin = 0, end = 0.9)
rs <- fd_soil_respiration()
# Violin plot of rs data by rep
rs %>% 
  ggplot(aes(x = replicate, y = soil_co2_efflux)) + 
  geom_jitter(aes(color = replicate), alpha = 0.2) +
  geom_violin(aes(color = replicate), fill = NA, size = 1) + 
  scale_color_manual(values = pal) + theme_bw() + 
  labs(y = expression(Soil~Respiration~(μmol~CO[2]~m^-2~s^-1)))
````

**Comment by atkinsjeff** [comment]
I went through and made everything lower case and removed all the camel case too...replacing with "_" because that was noted in the issues.

**Comment by atkinsjeff** [comment]
This looks stellar though!

**Comment by bpbond** [comment]
Where is it?!? </whine> I tried building the Rmd file on this branch and no figures appeared. 😕

**Comment by atkinsjeff** [comment]
I put the code into my local but haven't merged to remote yet

Jeff Atkins, Ph.D
Department of Biology
Virginia Commonwealth University

**Comment by stephpenn1** [comment]
Has this already been incorporated? Should I close this PR?

**Pull request closed without merging**
