### PR TITLE
draft of more complete meta data file

### PR DESCRIPTION
**Pull request by atkinsjeff**

### CODE REVIEW

**Comment by atkinsjeff** [comment]
what about this?

**Comment by bpbond** [comment]
What's `NSP_id` mean?

**Comment by atkinsjeff** [comment]
the nested subplot. We can call those things what ever, but those are the sampling locations within the plot. 

image

**Comment by atkinsjeff** [comment]
Granted, GPS coordinates need to be acquired for everything that is not a plot center.

**Comment by bpbond** [comment]
I appreciate the NEON-style approach with everything in one table–it has some advantages, although there's a lot of repetition. In contrast, here's the same data in a different-table approach:

**Plot table**

Replicate | Plot | Longitude | Latitude | Plot_area_m2
-- | -- | -- | -- | --
A | 1 | 45.563404 | -84.728465 | 5000
A | 2 | 45.56418 | -84.727971 | 5000
A | 3 | 45.562995 | -84.727099 | 5000
A | 4 | 45.563701 | -84.726382 | 5000
B | 1 | 45.556685 | -84.72685 | 5000
B | 2 | 45.555822 | -84.726783 | 5000
B | 3 | 45.556236 | -84.725704 | 5000
B | 4 | 45.556248 | -84.724383 | 5000
C | 1 | 45.562496 | -84.707799 | 5000
C | 2 | 45.563128 | -84.706747 | 5000
C | 3 | 45.563069 | -84.705397 | 5000
C | 4 | 45.563751 | -84.703382 | 5000
D | 1 | 45.560897 | -84.70701 | 5000
D | 2 | 45.56203 | -84.705022 | 5000
D | 3 | 45.560387 | -84.704516 | 5000
D | 4 | 45.561776 | -84.70364 | 5000

**Subplot table**

Replicate | Plot | Subplot | Latitude | Longitude | Subplot_area_m2
-- | -- | -- | -- | -- | --
A | 1 | E | 45.563404 | -84.728465 | 1000
A | 1 | W | 45.563404 | -84.728465 | 1000
A | 2 | E | 45.56418 | -84.727971 | 1000
A | 2 | W | 45.56418 | -84.727971 | 1000
A | 3 | E | 45.562995 | -84.727099 | 1000
A | 3 | W | 45.562995 | -84.727099 | 1000
A | 4 | E | 45.563701 | -84.726382 | 1000
A | 4 | W | 45.563701 | -84.726382 | 1000
B | 1 | E | 45.556685 | -84.72685 | 1000
B | 1 | W | 45.556685 | -84.72685 | 1000
B | 2 | E | 45.555822 | -84.726783 | 1000
B | 2 | W | 45.555822 | -84.726783 | 1000
B | 3 | E | 45.556236 | -84.725704 | 1000
B | 3 | W | 45.556236 | -84.725704 | 1000
B | 4 | E | 45.556248 | -84.724383 | 1000
B | 4 | W | 45.556248 | -84.724383 | 1000
C | 1 | E | 45.562496 | -84.707799 | 1000
C | 1 | W | 45.562496 | -84.707799 | 1000
C | 2 | E | 45.563128 | -84.706747 | 1000
C | 2 | W | 45.563128 | -84.706747 | 1000
C | 3 | E | 45.563069 | -84.705397 | 1000
C | 3 | W | 45.563069 | -84.705397 | 1000
C | 4 | E | 45.563751 | -84.703382 | 1000
C | 4 | W | 45.563751 | -84.703382 | 1000
D | 1 | E | 45.560897 | -84.70701 | 1000
D | 1 | W | 45.560897 | -84.70701 | 1000
D | 2 | E | 45.56203 | -84.705022 | 1000
D | 2 | W | 45.56203 | -84.705022 | 1000
D | 3 | E | 45.560387 | -84.704516 | 1000
D | 3 | W | 45.560387 | -84.704516 | 1000
D | 4 | E | 45.561776 | -84.70364 | 1000
D | 4 | W | 45.561776 | -84.70364 | 1000

**Nested subplot table**

Subplot | Nested_subplot | Nested_subplot_area_m2
-- | -- | --
E | 1 | 1
W | 1 | 1
E | 2 | 1
W | 2 | 1
E | 3 | 1
W | 3 | 1
E | 4 | 1
W | 4 | 1
E | 5 | 1
W | 5 | 1
E | 6 | 1
W | 6 | 1
E | 7 | 1
W | 7 | 1
E | 8 | 1
W | 8 | 1
E | 9 | 1
W | 9 | 1

The disadvantage here is that not everything is one place–you need to combine them through a two `merge()`s to produce the one single table. The advantage is (i) it's easier to find things I think, and (ii)  we've eliminated a lot of repetition, encoding in 66 lines what the full table needs 314 lines to do.

**Comment by ashiklom** [comment]
I'm going to second @bpbond's approach here. In addition to what he said, another nice thing about splitting this data up in this way ("database normalization") is that it makes it easier to append additional information about the plots later on.

Also, something @bpbond and I were discussing earlier is that, by eschewing R's builtin `data` mechanism in favor of our own custom functions, we can easily separate how the data are stored (across many smaller tables) from the various ways in which they are used (combined long tables, wide tables, etc.). For instance, if the long table from this PR is a common starting point for analyses, we can have a function like the following (we would probably implement in base R, but it's easier to illustrate with `dplyr`):

```r
fd_plots_detailed <- function() {
  fd_plots() %>%
    inner_join(fd_subplots()) %>%
    inner_join(fd_nested_subplots())
}
```

...so you could start your analysis as if you had the long table without having to bother `joining` everything yourself every time.

**Comment by atkinsjeff** [comment]
Love it. Clean and elegant.

**Comment by bpbond** [comment]
@atkinsjeff OK, if you're OK with that, I'm going to close this PR and open a new one.

**Pull request closed without merging**
